### ISSUE TITLE
test.py tensorflow ran out of memory trying to allocate, with big Image or lr_dir have many Image.

### ISSUE THREAD

**Issue by ICEET** [JueLin/Residual_Channel_Attention_Network_Tensorflow#2]
tensorflow ran out of memory trying to allocate, with big Image or lr_dir have many Image.
I think can split the Image to block or use batch-size to solve the problem, But I no idea how to do.
*test in GTX 1080 TI.
e.g:
samll Image *10 --cnn_type='rcan' --scale=2
pass no error
1920x1080 Image *2 --cnn_type='rcan' --scale=2
pass no error
1920x1080 Image *3  --cnn_type='rcan' --scale=2
 tensorflow ran out of memory trying to allocate
1920x1080 Image *1  --cnn_type='rcan' --scale=4
 tensorflow ran out of memory trying to allocate

**Comment by JueLin** [comment]
The RCAN network itself is pretty deep. Plus the computation needed for sub-pixel convolution grows O(n^2) as spatial dimension of input image increases. In this case, a GPU cannot accommodate this amount of computations.

You can try break each single image as batch of sub-images. Then feed batch of reasonable size to Tensorflow session. At last,  organize each super-resolved patches back to one single image.
